grails-app/domain/kiosk/Customer.groovy
package kiosk

class Customer {

    String firstName
    String lastName
    Long phone
    String email
    Integer totalPoints

    static hasMany = [awards: Award, onlineOrders: OnlineOrder]
    static constraints = {
        lastName (nullable: true)
        totalPoints(nullable: true)
        email(nullable: true, email: true)
    }

    static mapping = {
        onlineOrders lazy: false
    }
}

grails-app/domain/kiosk/OrderItem.groovy
package kiosk

class OrderItem {
    Integer qty
    Float total
    static transients = ['selected']
    Boolean selected
    static belongsTo = [onlineOrder: OnlineOrder, product: Product]

    static constraints = {
    }
}

grails-app/domain/kiosk/Product.groovy
package kiosk

class Product {
    String name
    String sku
    Float price

    static hasMany = [orderItems: OrderItem]
    static constraints = {
    }
}

grails-app/controllers/kiosk/CustomerController.groovy
package kiosk

import org.apache.commons.logging.LogFactory

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CustomerController {

    private static final log = LogFactory.getLog(this)
    def customerService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Customer.list(params), model: [customerInstanceCount: Customer.count()]
    }

    def home(){
    }

    def orders(Customer customerInstance){
        def orders = customerInstance ? OnlineOrder.findAllByCustomer(customerInstance) : []
        render ('customerorder', model: [orders: orders])
    }

    def customerOrder(Customer customerInstance){
        def orders = customerInstance ? OnlineOrder.findAllByCustomer(customerInstance) : []
        render(view: 'customerorder', model: [orders: orders, customerInstance: customerInstance])
    }

    def newOrder(){
        render(view: 'neworder', model: [productList: Product.list(params), orderItemInstance: new OrderItem(params)])
    }

    def show(Customer customerInstance) {
        render (view: 'show', model: [customerInstance: customerInstance])
    }

    def create() {
        respond new Customer(params)
    }
    def processCheckIn(Customer lookupInstance){
        def (customerInstance, welcomeMessage) = customerService.processCheckIn(lookupInstance)
        session.customerInstance = customerInstance
        //session["loggedInCustomer"] = customerInstance.firstName
        log.debug("found customer  ${customerInstance.firstName}")
        render(view: 'customerorder', model: [customerInstance: customerInstance, welcomeMessage: welcomeMessage])
    }

    def checkIn(){
        def customerInstance = new Customer(params)
        render(view: 'checkin', model: [customerInstance: customerInstance])
    }

    def delBtn(){
        redirect(action: 'index', controller: 'home')
    }

    def logout(){
        session.customerInstance = null
        session.invalidate()
    }

    def checkOut(){
        def checkedProducts = params.list('products')
        def customer = params.customer
        def customerInstance = Customer.get(customer)
        //get list of selected products, this will return only products
        def selectedProducts = Product.getAll(checkedProducts)
        def orderTotal = 0.00
        //create a new onlineorder
        //we iterate over the results in the selected product
        def onlineOrder = new OnlineOrder(orderNumber: customerService.generateOrderNumber(),
                orderDate: new Date())
        onlineOrder.save()
        for(result in selectedProducts){
            //logic to create an orderitem comes here
            def orderItem = new OrderItem()
            orderItem.product = result
            orderItem.qty = params.qty
            orderItem.total = params.total

            //we get sum of each order item in list
            orderTotal =+ params.total
            //we have save orderitem
            orderItem.save()
            onlineOrder.addToOrderItems(orderItem)
        }

        onlineOrder.orderTotal = orderTotal
        onlineOrder.save(flush: true)

        //save onlineorder to customer
        customerInstance.addToOnlineOrders(onlineOrder)
        customerInstance.save(flush: true)
        redirect(action: 'customerOrder')
    }


    @Transactional
    def save(Customer customerInstance) {
        if (customerInstance == null) {
            notFound()
            return
        }

        if (customerInstance.hasErrors()) {
            respond customerInstance.errors, view: 'create'
            return
        }

        customerInstance.save flush: true
        redirect(action: 'index')
//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.created.message', args: [message(code: 'customer.label', default: 'Customer'), customerInstance.id])
//                redirect customerInstance
//            }
//            '*' { respond customerInstance, [status: CREATED] }
//        }
    }

    def edit(Customer customerInstance) {
        render(view: 'edit', model: [customerInstance: customerInstance])
    }

    @Transactional
    def update(Customer customerInstance) {
        if (customerInstance == null) {
            notFound()
            return
        }

        if (customerInstance.hasErrors()) {
            respond customerInstance.errors, view: 'edit'
            return
        }

        customerInstance.save flush: true
        redirect(action: 'index')
//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.updated.message', args: [message(code: 'Customer.label', default: 'Customer'), customerInstance.id])
//                redirect customerInstance
//            }
//            '*' { respond customerInstance, [status: OK] }
//        }
    }

    @Transactional
    def delete(Customer customerInstance) {

        if (customerInstance == null) {
            notFound()
            return
        }

        customerInstance.delete flush: true
        redirect(action: 'index')
//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Customer.label', default: 'Customer'), customerInstance.id])
//                redirect action: "index", method: "GET"
//            }
//            '*' { render status: NO_CONTENT }
//        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'customer.label', default: 'Customer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/customer/_checkinForm.gsp
<!--form for checking in customer -->
<div class="container">
    <div class="row">
        <g:form url="[resource: customerInstance, action: 'processCheckIn']">
            <div class="col-sm-6 col-sm-offset-3">
                <g:textField name="phone" id="phone" placeholder="Enter your phone number" class="form-control" value="${customerInstance?.phone}"/>
                <!-- spacer -->
                <div class="row">
                    <h4></h4>
                </div>
                <!-- 1st set of number buttons -->
                <div class="row">
                    <div class="col-sm-4">
                        <input type="button" value="1" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" value="2" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" value="3" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                </div>

                <div class="row">
                    <h4></h4>
                </div>
                <!-- 2nd set of number buttons -->
                <div class="row">
                    <div class="col-sm-4">
                        <input type="button" value="4" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" value="5" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" value="6" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                </div>

                <div class="row">
                    <h4></h4>
                </div>
                <!-- 3rd set of number buttons -->
                <div class="row">
                    <div class="col-sm-4">
                        <input type="button" value="7" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" value="8" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" value="9" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                </div>

                <div class="row">
                    <h4></h4>
                </div>
                <!-- 4th set of number buttons -->
                <div class="row">
                    <div class="col-sm-4">
                        <g:link  class="btn btn-danger btn-block btn-lg" action="delBtn" controller="customer">Del</g:link>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" value="0" class="btn btn-primary btn-block btn-lg" onclick="keyPad(this.value);"/>
                    </div>
                    <div class="col-sm-4">
                        <g:submitButton value="Go" name="Go" class="btn btn-success btn-block btn-lg" />
                    </div>
                </div>
            </div>
        </g:form>
    </div>
    <script>
        function keyPad(num){
            var txt = document.getElementById("phone").value;
            txt += num;
            document.getElementById("phone").value = txt;

        }
    </script>
</div>

grails-app/views/customer/_customerForm.gsp
<div class="form-horizontal">
    <div class="form-group">
        <label class="control-label col-sm-2" for="firstName">First Name</label>
        <div class="col-sm-10">
            <input type="text" name="firstName" class="text-input" value="${customerInstance?.firstName}" />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="lastName">Last Name</label>
        <div class="col-sm-10">
            <input type="text" name="lastName" class="text-input" value="${customerInstance?.lastName}" />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" fo="phone">Phone</label>
        <div class="col-sm-10">
            <input type="text" name="phone" class="text-input" value="${customerInstance?.phone}" />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email</label>
        <div class="col-sm-10">
            <input type="text" name="email" class="text-input" value="${customerInstance?.email}" />
        </div>
    </div>
</div>

grails-app/views/customer/checkin.gsp
<!doctype html>
<html lang="en">
    <head>
        <meta name="layout" content="home">
        <title>Kiosk-Customer Check-In</title>
       <link href="${resource(dir:'css', file:'bootstrap.min.css')}" rel="stylesheet" />
    </head>

    <body>
        <g:render template="checkinForm"/>
    </body>
</html>

grails-app/views/customer/checkout.gsp
<html>
    <head>
        <title>Kiosk-Customer Checkout</title>
        <meta name="layout" content="home">
    </head>
    <body>
        <div class="panel panel-default">
            <div class="panel-heading">Order Items</div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <tr>
                        <th></th><th></th><th></th>
                    </tr>
                    <g:each>
                        <tr>
                            <td></td><td></td><td></td>
                        </tr>
                    </g:each>
                </table>
            </div>
        </div>
    </body>
</html>

grails-app/views/customer/create.gsp
<html>
<head>
    <meta name="layout" content="home">
    <title>Kiosk-Customer</title>
</head>

<body>
    <g:form url="[resource: customerInstance, action:'save']" method="POST">
        <div class="panel panel-default">
            <div class="panel-heading">New Customer</div>
            <div class="panel-body">
                <g:render template="customerForm" />
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-2 col-sm-offset-10">
                        <g:submitButton name="save" value="Save" class="btn btn-sm btn-primary"/>
                        <g:link action="index" class="btn btn-warning btn-sm">Cancel</g:link>
                    </div>
                </div>
            </div>
        </div>
    </g:form>
</body>
</html>

grails-app/views/customer/customerorder.gsp
<html>
<head>
    <title>Kiosk-Customer Order</title>
    <meta name="layout" content="home">
</head>

<body>
    <div class="panel panel-default">
        <div class="panel-heading">Customer Orders</div>
        <div class="panel-body">
            <g:include view="customer/orders.gsp" />
        </div>
        <div class="panel-footer">
            <g:link controller="customer" action="newOrder" params="[customer: customerInstance.id]" class="btn btn-primary btn-block btn-sm">New Order</g:link>
        </div>
    </div>
</body>
</html>

grails-app/views/customer/edit.gsp
<html>
    <head>
        <meta name="layout" content="home">
    </head>
    <body>
        <g:form url="[resource: customerInstance, action:'update']" method="PUT">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Customer</div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="firstName">First Name</label>
                            <div class="col-sm-10">
                                <input type="text" name="firstName" class="text-input" value="${customerInstance?.firstName}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="lastName">Last Name</label>
                            <div class="col-sm-10">
                                <input type="text" name="lastName" class="text-input" value="${customerInstance?.lastName}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" fo="phone">Phone</label>
                            <div class="col-sm-10">
                                <input type="text" name="phone" class="text-input" value="${customerInstance?.phone}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="email">Email</label>
                            <div class="col-sm-10">
                                <input type="text" name="email" class="text-input" value="${customerInstance?.email}" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-sm-2 col-sm-offset-10">
                            <g:actionSubmit name="update" value="Update" class="btn btn-info"/>
                            <g:link action="index" controller="customer" class="btn btn-warning">Cancel</g:link>
                        </div>
                    </div>
                </div>
            </div>
        </g:form>
       
    </body>
</html>

grails-app/views/customer/index.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
    <meta name="layout" content="home">
</head>

<body>
    <div class="panel panel-default">
        <div class="panel-heading">Customers</div>
        <div class="panel-body">
            <g:include view="customer/list.gsp" />
        </div>
        <div class="panel-footer">
            <g:link class="btn btn-primary btn-sm btn-block" action="create">New Customer</g:link>
        </div>
    </div>

</body>
</html>

grails-app/views/customer/list.gsp
<table class="table table-bordered">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Phone</th>
        <th>Total Points</th>
        <th>Action</th>
    </tr>
    <g:each in="${customerInstanceList}" var="customerInstance">
        <tr>
            <td>${customerInstance.firstName}</td>
            <td>${customerInstance.lastName}</td>
            <td>${customerInstance.phone}</td>
            <td>${customerInstance.totalPoints}</td>
            <td><g:link id="${customerInstance.id}" action="show" class="btn btn-primary btn-sm">Select</g:link> | <g:link class="btn btn-success btn-sm" action="customerOrder" id="${customerInstance.id}">Orders</g:link></td>
        </tr>
    </g:each>
</table>

grails-app/views/customer/neworder.gsp

<html>
<head>
    <title>Kiosk-New Order</title>
    <meta name="layout" content="home">
    <style>
        tfoot{
            font-size: larger;
        }
    </style>
</head>

<body>
    <div class="panel panel-default">
        <div class="panel-heading">New Customer Order</div>
        <div class="panel-body">
            <div class="alert alert-info">Select Product to add to order</div>
            <table class="table table-bordered table-striped" id="newOrderTable">
                <tr>
                    <th>Select</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
                <g:each in="${productList}" var="productInstance">
                    <tr>
                        <td><g:checkBox name="products" value="${productInstance?.id}" checked="false"/></td>
                        <td>${productInstance?.name}</td>
                        <td class="price">${productInstance?.price}</td>
                        <td class="qty"><input type="number" id="itemQty" name="itemQty" value="${orderItemInstance?.qty}"/> </td>
                        <td class="total">${orderItemInstance?.total}</td>
                    </tr>
                </g:each>
                <tfoot>
                    <tr>
                        <td colspan="4">Order Total</td>
                        <td class="orderTotal"></td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-offset-2 col-sm-10">
                    <g:link class="btn btn-sm btn-primary">Checkout</g:link>
                    <g:link class="btn btn-sm btn-warning">Cancel</g:link>
                </div>
            </div>
        </div>
    </div>
    <!-- javascript function to update total pricing -->
    <script type="text/javascript">
        //trigger on change of qty
        $(".qty").change(function(){
            var row = $(this).closest("tr"); //Find the row
            var qty = row.find("input[name='itemQty']").val(); //Find the qty
            var price = row.find(".price").text(); //Find the price
            var total = price * qty;
            row.find(".total").text(total);
            var checked = row.find("input[name='products']");
            alert(checked);
            var sum = 0;
            if(checked.attr('checked')){
                sum+=total;
                $(".orderTotal").text(sum);
            }
        });

    </script>
</body>
</html>

grails-app/views/customer/orders.gsp
<table class="table table-bordered table-striped">
    <tr>
        <th>Order Number</th>
        <th>Order Total</th>
        <th>Order Date</th>
    </tr>
    <tbody>
        <g:if test="${orders.size() < 1}">
            No orders for customer
        </g:if>
        <g:else>
            <g:each in="${orders}" var="orderInstance">
                <tr>
                    <td>${orderInstance.orderNumber}</td>
                    <td>${orderInstance.orderTotal}</td>
                    <td>${orderInstance.orderDate}</td>
                    <td><g:link>Details</g:link></td>
                </tr>
            </g:each>
        </g:else>
    </tbody>

</table>

grails-app/views/customer/show.gsp

<html>
<head>
    <title></title>
    <meta name="layout" content="home">
</head>

<body>
    <div class="panel panel-default">
        <div class="panel-heading">Customer Detail</div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-2" for="firstName">First Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="firstName" class="text-input" value="${customerInstance?.firstName}" readonly="true"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="lastName">Last Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="lastName" class="text-input" value="${customerInstance?.lastName}" readonly="true"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" fo="phone">Phone</label>
                    <div class="col-sm-10">
                        <input type="text" name="phone" class="text-input" value="${customerInstance?.phone}" readonly="true"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="email">Email</label>
                    <div class="col-sm-10">
                        <input type="text" name="email" class="text-input" value="${customerInstance?.email}" readonly="true"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="totalPoints">Total Points</label>
                    <div class="col-sm-10">
                        <input type="text" name="totalPoints" class="text-input" value="${customerInstance?.totalPoints}" readonly="true"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-offset-2 col-sm-10">
                    <g:form url="[resource: customerInstance, action: 'delete']" method="DELETE">
                        <g:link resource="${customerInstance}" class="btn btn-primary" action="edit">Edit</g:link>
                        <g:actionSubmit value="Delete" class="btn btn-danger"/>
                        <g:link action="index" controller="customer" class="btn btn-warning">Cancel</g:link>
                    </g:form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>