grails-app/domain/kiosk/Customer.groovy
package kiosk

class Customer {

    String firstName
    String lastName
    Long phone
    String email
    Integer totalPoints

    static hasMany = [awards: Award, onlineOrders: OnlineOrder]
    static constraints = {
        lastName (nullable: true)
        totalPoints(nullable: true)
        email(nullable: true, email: true)
    }

    static mapping = {
        onlineOrders lazy: false
    }
}

grails-app/views/layouts/_admin.gsp
<!doctype html>
<html>
    <head>
        <title></title>
        <asset:stylesheet
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target="#adminNavBar">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand">Kiosk</a>
                </div>

                <!-- begin nav links -->
                <div class="collapse navbar-collapse" id="adminNavBar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><g:link controller="person" action="product">Products</g:link></li>
                        <li><g:link controller="person" action="index">Staff</g:link></li>
                        <li><g:link controller="person" action="logout">Logout</g:link></li>
                    </ul>
                </div>
            </div>
        </nav><!-- end of navbar-->
        <div class="container">
            <g:layoutBody></g:layoutBody>
        </div>

    </body>
</html>

grails-app/views/layouts/_customer.gsp
<!doctype html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="${resource(dir:'css', file:'bootstrap.min.css')}" />
        <script src="${resource(dir: 'js', file: 'jquery-1.11.3.js')}" />
        <script src="${resource(dir: 'javascripts', file: 'bootstrap.min.js')}"></script>
    </head>
    <body>
        <!--nav bar for customer -->
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target="#customerNav">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <g:link class="navbar-brand">Kiosk</g:link>

                <div class="collapse navbar-collapse" id="customerNav">
                    <ul class="nav navbar-nav navbar-right">
                        <li><g:link url="[action: 'orders', controller: 'customer']">Orders</g:link></li>
                        <li c   lass="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Welcome ${session.customerInstance?.firstName}<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><g:link url="[action:'profile', controller:'customer']">Profile</g:link></li>
                                <li><g:link>Logout</g:link></li>

                            </ul>
                        </li>


                    </ul>
                </div>
            </div>
        </nav><!-- end navbar-->
        <div class="container">
            <g:layoutBody>
                <div class="row">
                    <div class="col-sm-offset-6 col-sm-3">
                        <div class="jumbotron">

                        </div>
                    </div>
                </div>
            </g:layoutBody>
        </div>
    </body>
</html>

grails-app/views/layouts/home.gsp
<!doctype html>
<html>
<head>
    <title>
        <g:layoutTitle default="Kiosk"></g:layoutTitle>
    </title>
    <asset:stylesheet src="bootstrap.min.css"/>
    <asset:javascript src="jquery.js" />
    <g:layoutHead/>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapse" data-toggle="toggle" data-target="#crudNav">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="${createLinkTo(uri: '/index1.gsp')}">Kiosk</a>
            </div>

            <div class="collapse navbar-collapse" id="crudNav">
                <ul class="nav navbar-nav navbar-right">
                    <li><g:link controller="customer" action="index">Customer</g:link></li>
                    <li><g:link controller="person" action="index">Staff</g:link></li>
                    <li><g:link controller="product" action="index">Product</g:link></li>
                </ul>
            </div>
        </div>
        
    </nav>
    <div class="container">
        <div class="row">
            <g:layoutBody/>
        </div>
    </div>
</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>