grails-app/domain/kiosk/Person.groovy
package kiosk

class Person {

    String firstname
    String lastname
    Long phone
    String email
    String uname
    String pwd

    static constraints = {
        phone(nullable: true)
    }
}

grails-app/controllers/kiosk/PersonController.groovy
package kiosk

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PersonController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Person.list(params), model: [personInstanceCount: Person.count()]
    }

    def show(Person personInstance) {
//        respond personInstance, view: 'show'
        render(view: 'show', model: [personInstance: personInstance])
    }


    def create() {
        [personInstance: new Person(params)]
        //respond new Person(params)
    }

    def signin(){
        render(view: 'signin')
    }

    def handleLogin(){
        def user = Person.findByUnameAndPwd(params.uname, params.pwd)
        if(user !=null){
            session.user = user
            redirect(action: 'index')
        }else{
            redirect(action: 'signin')
        }
    }

    def product(){
        redirect(action: 'index', controller: 'product')
    }

    def logout(){
        session.user = null
        session.invalidate()
        redirect(action: 'signin')
    }

    @Transactional
    def save(Person personInstance) {
        if (personInstance == null) {
            notFound()
            return
        }

        if (personInstance.hasErrors()) {
            respond personInstance.errors, view: 'create'
            return
        }

        personInstance.save flush: true
        redirect action: 'index'
//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.created.message', args: [message(code: 'person.label', default: 'Person'), personInstance.id])
//                redirect personInstance
//            }
//            '*' { respond personInstance, [status: CREATED] }
//        }
    }

//    def edit(Person personInstance) {
//        respond personInstance, view: 'edit'
//    }

    def edit(Person personInstance){
        render(view: 'edit', model: [personInstance: personInstance])
    }

    @Transactional
    def update(Person personInstance) {
        if (personInstance == null) {
            notFound()
            return
        }

        if (personInstance.hasErrors()) {
            respond personInstance.errors, view: 'edit'
            return
        }

        if(personInstance.save( flush: true)){
            redirect(action: 'index')
        }else{
            redirect(action: 'edit', [personInstance: personInstance])
        }



//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.updated.message', args: [message(code: 'Person.label', default: 'Person'), personInstance.id])
//                redirect personInstance
//            }
//            '*' { respond personInstance, [status: OK] }
//        }
    }

    @Transactional
    def delete(Person personInstance) {
        if (personInstance == null) {
            notFound()
            return
        }

        personInstance.delete flush: true
        redirect action: "index"



//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Person.label', default: 'Person'), personInstance.id])
//                redirect action: "index", method: "GET"
//            }
//            '*' { render status: NO_CONTENT }
//        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'person.label', default: 'Person'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/person/_staffForm.gsp
<div class="form-horizontal">
    <div class="form-group">
        <label class="control-label col-sm-2" for="lastname">Last Name</label>
        <div class="col-sm-10">
            <input type="text" name="lastname" class="text-input" value="${personInstance.lastname}"/>
        </div>

    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="firstname">First Name</label>
        <div class="col-sm-10">
            <input type="text"  name="firstname" class="text-input" value="${personInstance.firstname}"/>
        </div>

    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="phone">Phone</label>
        <div class="col-sm-10">
            <input type="text" id="phone" name="phone" class="text-input" value="${personInstance.phone}"/>
        </div>

    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email</label>
        <div class="col-sm-10">
            <input type="text" id="email" name="email" class="text-input" value="${personInstance?.email}"/>
        </div>

    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="uname">Username</label>
        <div class="col-sm-10">
            <input type="text" id="uname" name="uname" class="text-input" value="${personInstance.uname}"/>
        </div>

    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Password</label>
        <div class="col-sm-10">
            <input type="text" id="pwd" name="pwd" class="text-input" value="${personInstance.pwd}"/>
        </div>

    </div>
</div>

grails-app/views/person/create.gsp

<html>
<head>
    <meta name="layout" content="home">
    <title></title>
</head>

<body>
    <g:form url="[resource: personInstance, action: 'save']" method="POST">
        <div class="panel-default panel">
            <div class="panel-heading">New Staff</div>
            <div class="panel-body">
                <g:render template="staffForm"/>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-offset-2 col-sm-10">
                        <g:submitButton name="save" value="Save" class="btn btn-sm btn-primary" />
                        <g:link action="index" class="btn btn-sm btn-warning">Cancel</g:link>
                    </div>
                </div>
            </div>
        </div>
    </g:form>
</body>
</html>

grails-app/views/person/edit.gsp

<html>
<head>
    <meta name="layout" content="home">
    <title></title>
</head>

<body>

    <g:form url="[resource: personInstance, action: 'update']" method="PUT">
        <div class="panel panel-default">
            <div class="panel-heading">Edit Staff</div>
            <div class="panel-body">
                    <g:render template="staffForm"/>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <g:actionSubmit value="Update" class="btn btn-info btn-sm col-sm-2 "/>
                    <g:link controller="person" action="index" class="btn btn-warning btn-sm col-sm-2">Cancel</g:link>
                </div>
            </div>
        </div>
    </g:form>
</body>
</html>

grails-app/views/person/index.gsp
<html>
    <head>
        <meta name="layout" content="home">
    </head>
    <body>
        <div class="panel panel-default">
            <div class="panel-heading">Kiosk Staff</div>
            <div class="panel-body">
                <g:include view="person/list.gsp" />
            </div>
            <div class="panel-footer">
                <g:link class="btn btn-primary btn-sm btn-block" action="create">New Staff</g:link>
            </div>
        </div>
    </body>
</html>

grails-app/views/person/list.gsp

    <table class="table table-bordered">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
        <g:each in="${personInstanceList}" var="personInstance">
            <tr>
                <td>${personInstance?.firstname}</td>
                <td>${personInstance?.lastname}</td>
                <td>${personInstance?.phone}</td>
                <td>${personInstance?.email}</td>
                %{--<td>${staff.Role}</td>--}%
                <td><g:link id="${personInstance.id}" action="show" class="btn btn-sm btn-info">Select</g:link>
                </td>
            </tr>
        </g:each>
    </table>

grails-app/views/person/show.gsp
<html>
<head>
    <title>Staff Detail</title>
    <meta name="layout" content="home">
</head>

<body>
    <div class="panel panel-default">

            <div class="panel-heading">Staff Detail</div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="fname">First Name</label>
                        <div class="col-sm-10">
                            <input readonly="true" id="fname" value="${personInstance.firstname}"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="lnane">Last Name</label>
                        <div class="col-sm-10">
                            <input readonly="true" id="lname"value="${personInstance.lastname}"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="phone">Phone</label>
                        <div class="col-sm-10">
                            <input readonly="true" value="${personInstance.phone}" id="phone"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="email">Email</label>
                        <div class="col-sm-10">
                            <input readonly="true" value="${personInstance.email}" id="email"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="uname">Username</label>
                        <div class="col-sm-10">
                            <input type="text" readonly="true" id="uname" value="${personInstance.uname}"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="pwd">Password</label>
                        <div class="col-sm-10">
                            <input type="password" id="pwd" readonly="true" value="${personInstance.pwd}"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <g:form url="[action: 'delete', resource: personInstance]" method="DELETE">
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-10">
                            <g:link action="edit" resource="${personInstance}" class="btn btn-sm btn-primary">Edit</g:link>
                            <g:actionSubmit value="Delete" class="btn btn-sm btn-danger"/>
                        </div>
                    </div>
                </g:form>
            </div>
    </div>
</body>
</html>

grails-app/views/person/signin.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="home">
    <title>Kiosk - Signin</title>
    <link rel="stylesheet" href="${resource(dir:'stylesheets', file: 'bootstrap.min.css')}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <g:form action="handleLogin" controller="person">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Staff CheckIn
                        </div>
                        <div class="panel-body">
                            <form class="form-horizontal">
                                <div class="form-group-sm">
                                    <label for="uname" class="col-sm-2"></label>
                                    <div class="col-sm-10">
                                        <input name="uname"  value="${personInstance?.uname}"/>
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <label for="pwd" class="col-sm-2"></label>
                                    <div class="col-sm-10">
                                        <input name="pwd" value="${personInstance?.pwd}"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="panel-footer">
                            <g:submitButton name="signin" value="Sign In"/>
                        </div>
                    </div>
                </g:form>
            </div>
        </div>
    </div>
</body>

</html>


grails-app/views/person/staffcheckin.gsp
<!doctype html>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>