grails-app/domain/kiosk/OrderItem.groovy
package kiosk

class OrderItem {
    Integer qty
    Float total
    static transients = ['selected']
    Boolean selected
    static belongsTo = [onlineOrder: OnlineOrder, product: Product]

    static constraints = {
    }
}

grails-app/controllers/kiosk/OrderItemController.groovy
package kiosk


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class OrderItemController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond OrderItem.list(params), model: [orderItemInstanceCount: OrderItem.count()]
    }

    def show(OrderItem orderItemInstance) {
        respond orderItemInstance
    }

    def create() {
        respond new OrderItem(params)
    }

    @Transactional
    def save(OrderItem orderItemInstance) {
        if (orderItemInstance == null) {
            notFound()
            return
        }

        if (orderItemInstance.hasErrors()) {
            respond orderItemInstance.errors, view: 'create'
            return
        }

        orderItemInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'orderItem.label', default: 'OrderItem'), orderItemInstance.id])
                redirect orderItemInstance
            }
            '*' { respond orderItemInstance, [status: CREATED] }
        }
    }

    def edit(OrderItem orderItemInstance) {
        respond orderItemInstance
    }

    @Transactional
    def update(OrderItem orderItemInstance) {
        if (orderItemInstance == null) {
            notFound()
            return
        }

        if (orderItemInstance.hasErrors()) {
            respond orderItemInstance.errors, view: 'edit'
            return
        }

        orderItemInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'OrderItem.label', default: 'OrderItem'), orderItemInstance.id])
                redirect orderItemInstance
            }
            '*' { respond orderItemInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(OrderItem orderItemInstance) {

        if (orderItemInstance == null) {
            notFound()
            return
        }

        orderItemInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'OrderItem.label', default: 'OrderItem'), orderItemInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'orderItem.label', default: 'OrderItem'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/orderItem/_form.gsp
<%@ page import="kiosk.OrderItem" %>



<div class="fieldcontain ${hasErrors(bean: orderItemInstance, field: 'onlineOrder', 'error')} required">
	<label for="onlineOrder">
		<g:message code="orderItem.onlineOrder.label" default="Online Order" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="onlineOrder" name="onlineOrder.id" from="${kiosk.OnlineOrder.list()}" optionKey="id" required="" value="${orderItemInstance?.onlineOrder?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: orderItemInstance, field: 'product', 'error')} required">
	<label for="product">
		<g:message code="orderItem.product.label" default="Product" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="product" name="product.id" from="${kiosk.Product.list()}" optionKey="id" required="" value="${orderItemInstance?.product?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: orderItemInstance, field: 'qty', 'error')} required">
	<label for="qty">
		<g:message code="orderItem.qty.label" default="Qty" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="qty" type="number" value="${orderItemInstance.qty}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: orderItemInstance, field: 'total', 'error')} required">
	<label for="total">
		<g:message code="orderItem.total.label" default="Total" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="total" value="${fieldValue(bean: orderItemInstance, field: 'total')}" required=""/>

</div>

grails-app/views/orderItem/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'orderItem.label', default: 'OrderItem')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-orderItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-orderItem" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${orderItemInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${orderItemInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:orderItemInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/orderItem/edit.gsp
<%@ page import="kiosk.OrderItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'orderItem.label', default: 'OrderItem')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-orderItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-orderItem" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${orderItemInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${orderItemInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:orderItemInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${orderItemInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/orderItem/index.gsp
<%@ page import="kiosk.OrderItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'orderItem.label', default: 'OrderItem')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-orderItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-orderItem" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="orderItem.onlineOrder.label" default="Online Order" /></th>
					
						<th><g:message code="orderItem.product.label" default="Product" /></th>
					
						<g:sortableColumn property="qty" title="${message(code: 'orderItem.qty.label', default: 'Qty')}" />
					
						<g:sortableColumn property="total" title="${message(code: 'orderItem.total.label', default: 'Total')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${orderItemInstanceList}" status="i" var="orderItemInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${orderItemInstance.id}">${fieldValue(bean: orderItemInstance, field: "onlineOrder")}</g:link></td>
					
						<td>${fieldValue(bean: orderItemInstance, field: "product")}</td>
					
						<td>${fieldValue(bean: orderItemInstance, field: "qty")}</td>
					
						<td>${fieldValue(bean: orderItemInstance, field: "total")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${orderItemInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/orderItem/show.gsp
<%@ page import="kiosk.OrderItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'orderItem.label', default: 'OrderItem')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-orderItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-orderItem" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list orderItem">
			
				<g:if test="${orderItemInstance?.onlineOrder}">
				<li class="fieldcontain">
					<span id="onlineOrder-label" class="property-label"><g:message code="orderItem.onlineOrder.label" default="Online Order" /></span>
					
						<span class="property-value" aria-labelledby="onlineOrder-label"><g:link controller="onlineOrder" action="show" id="${orderItemInstance?.onlineOrder?.id}">${orderItemInstance?.onlineOrder?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${orderItemInstance?.product}">
				<li class="fieldcontain">
					<span id="product-label" class="property-label"><g:message code="orderItem.product.label" default="Product" /></span>
					
						<span class="property-value" aria-labelledby="product-label"><g:link controller="productRest" action="show" id="${orderItemInstance?.product?.id}">${orderItemInstance?.product?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${orderItemInstance?.qty}">
				<li class="fieldcontain">
					<span id="qty-label" class="property-label"><g:message code="orderItem.qty.label" default="Qty" /></span>
					
						<span class="property-value" aria-labelledby="qty-label"><g:fieldValue bean="${orderItemInstance}" field="qty"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${orderItemInstance?.total}">
				<li class="fieldcontain">
					<span id="total-label" class="property-label"><g:message code="orderItem.total.label" default="Total" /></span>
					
						<span class="property-value" aria-labelledby="total-label"><g:fieldValue bean="${orderItemInstance}" field="total"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:orderItemInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${orderItemInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>